import sqlite3 as sql

conn = sql.connect('product_substances.db')

cursor = conn.cursor()

# cleaning table - only for debug
cursor.execute("DROP TABLE IF EXISTS substances")

# create table of substances
cursor.execute(""" CREATE TABLE IF NOT EXISTS substances(
                name_of_substance text,
                e_code text,
                group text,
                function text,
                description text,
                harmfulness integer
)""")

# insert all substances into the tasble
cursor.execute(""" INSERT INTO substances VALUES
                ("5'-rybonukleotydy disodowe", "E 635", "Wzmacniacz smaku i zapachu" , "Substancje wzmacniające istniejący smak lub zapach środków spożywczych.", "Pełni rolę wzmacniacza smaku i zapachu. Istnieje wiele doniesień o niekorzystnym wpływie tego związku na nasze zdrowie, jednak nie jest możliwe wydanie wiążącej opinii.", NULL),
                ("azotyn sodu", "E 250", "Konserwant" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem spowodowanym obecnością mikroorganizmów lub chroni przed wzrostem mikroorganizmów patogennych.", "Jest dodawany do przetworów mięsnych i wyrobów garmażeryjnych w postaci mieszanki peklującej, w celu zabezpieczenia przed rozwojem bakterii beztlenowych. Jednak nadmierne pobranie azotynów może prowadzić do methemoglobinemii. Najbardziej narażone są niemowlęta. Nie należy ogrzewać peklowanych przetworów mięsnych, ponieważ w temperaturze powyżej 150°C powstają rakotwórcze nitrozoaminy. Przeprowadzono próby zastąpienia azotynów innymi substancjami, które hamowałyby wzrost Clostridium botulinum lub wytwarzanie toksyny botulinowej, jednak azotyny pozostają jedynym skutecznym środkiem.", NULL),
                ("azotan potasu", "E 252", "Konserwant" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem spowodowanym obecnością mikroorganizmów lub chroni przed wzrostem mikroorganizmów patogennych.", "Syntetyczny konserwant. Azotany są związkami chemicznymi o stosunkowo niskiej toksyczności dla ludzi, ale w organizmie ulegają przemianom do groźnych azotynów. Nadmierne pobranie azotynów lub redukcja azotanów do azotynów mogą doprowadzić do methemoglobinemii objawiającej się: sinicą, dusznością, sennością, bólem brzucha.", NULL),
                ("azorubina", "E 122", "barwniki syntetyczne" , "Barwi na czerwono.", "Jest syntetycznym barwnikiem, którego powinny unikać osoby uczulone na aspirynę. Może mieć szkodliwy wpływ na aktywność i skupienie uwagi u dzieci.", NULL),
                ("aspartam", "E 951", "Substancje słodzące" , "Słodząca, wzmacniacz smaku.", "Jest syntetyczną substancją słodzącą i wzmacniaczem smaku, która jest, aż 160-200 razy słodszy od sacharozy. Aspartam podczas trawienia rozkłada się na kwas asparaginowy, fenyloalaninę i nieznaczne ilości metanolu. Dlatego osoby chore na fenyloketonurię powinny zachować ostrożność! U tych osób wysokie stężenia fenyloalaniny oraz jej metabolitów we krwi działają toksycznie oraz mogą prowadzić do nieodwracalnego uszkodzenia mózgu. Z tego powodu na każdym opakowaniu jednostkowym produktu zawierającego aspartam musi być umieszczone ostrzeżenie: „zawiera źródło fenyloalaniny”. Niektóre badania wykazały, że po konsumpcji aspartamu mogą wystąpić w organizmie człowieka różne reakcje ze strony układu nerwowego, takie jak: bóle głowy, napady padaczkowe, upośledzenie percepcji, stany podniecenia, frustracji, depresji i ogólnego zaburzenia ustroju. Aspartam jest to substancja uznana za bezpieczną pod warunkiem zachowania dozwolonej dziennej dawki, czyli 40 mg aspartamu na 1 kg masy ciała.", NULL),
                ("askorbinian sodu", "E 301", "Przeciwutleniacz" , "Przeciwutleniająca, Regulująca kwasowość, Stabilizująca", "Nieszkodliwy w zastosowaniach spożywczych.", NULL),
                ("aromaty: jajo; wanilina", NULL, NULL , NULL, "wanilina jest substancją występującą naturalnie we włóknach drzew iglastych. Otrzymuje się ją z ligniny z drewna jodły (i innych drzew iglastych), albo w sposób syntetyczny z eugenolu lub gwajakolu. Stosowana jest jako substancja zapachowo-smakowa. Wanilina, pomimo że jest wyodrębniana z naturalnych surowców, jest zaliczana do syntetycznych środków zapachowych. Uznawana jest za bezpieczną dla zdrowia człowieka.", NULL),
                ("aromat dymu wędzarniczego", NULL, NULL , NULL, "ma właściwości barwiące i aromatyzujące.", NULL),
                ("antocyjany", "E 163", "Barwniki" , "Barwią na czerwono-purpurowo.", "Naturalne barwniki, które nie tylko są bezpieczne dla zdrowia, ale uważa się, że pełnią funkcje ochronne w organizmie. Antocyjany uszczelniają naczynia włosowate, zapobiegają obrzękom i posiadają aktywność przeciwzapalną. Ze względu na działanie antyoksydacyjne odgrywają ważną rolę w prewencji chorób nowotworowych. Antocyjany jako barwniki żywności wykazują działanie chroniące produkty spożywcze przed zepsuciem, ponieważ wykazują antagonistyczną aktywność wobec niektórych bakterii, wirusów i grzybów.", NULL),
                ("annato", "E 160b", "Barwniki naturalne" , "Nadaje lub przywraca żywności barwę na żółto-pomarańczowo.", "Barwnik żółty do pomarańczowego, kolor pochodzi od karotenoidów: biksyny i norbiksyny. Nie jest możliwe wydanie jednoznacznej opinii, jednak wiele badań wykazało niekorzystny wpływ tej substancji na zdrowie (zwłaszcza dzieci). Konieczne są dalsze badania.", NULL),
                ("amarant", "E 123", "Barwniki" , "Barwi na ciemnoczerwowno.", "Może nasilać objawy nietolerancji salicylanów oraz objawy astmy.", NULL),
                ("alginian sodu", "E 401", "Emulgator" , "Stabilizująca, Emulgująca, Rozpuszczalnik, Zagęszczająca.", "Naturalny, roślinny środek zagęszczający, do powlekania i substancja żelująca, która należy do grupy naturalnych hydrokoloidów pozyskiwanych z wodorostów morskich (alg brunatnych). Mogą korzystnie wpływać na zdrowie.", NULL),
                ("alginian propan-1;2-diolu", "E 405", "Emulgator" , "Klarująca, Stabilizująca, Emulgująca, Zagęszczająca", "Naturalny, roślinny środek zagęszczający, emulgator. U niektórych osób może powodować reakcje alergiczne, a w dużych dawkach efekt przeczyszczający.", NULL),
                ("alfa-tokoferol", "E 307", "Przeciwutleniacze" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem na skutek utleniania, takim jak jełczenie tłuszczu czy zmiana barwy.", "jest to syntetycznie produkowana witamina E. Witamina E uważana jest za jeden z najlepszych biologicznych przeciwutleniaczy. Dzięki właściwości antyoksydacyjnej zmniejsza ryzyko rozwoju chorób sercowo-naczyniowych oraz zmniejsza nasilenie procesów kancerogenezy. Spowalnia również ogólnoustrojowe procesy starzenia się organizmu, których przejawem jest m.in. spadek odporności.", NULL),
                ("aktywna mikroflora jogurtowa i dodatkowo kultury probiotyczne Lactobacillus acidophilus LA- 5; Bifidobacterium BB - 12", NULL, NULL , NULL, "probiotyki korzystnie działają w schorzeniach układu pokarmowego (syndrom jelita drażliwego, zapalenie jelit, biegunka), schorzeniach alergicznych (atopowe zapalenie skóry), a także zwiększają odporność organizmu. Bifidobakterie wzbogacają organizm człowieka w witaminy: B1, B2, B6, kwas foliowy i nikotynowy, korzystnie działają na przyswajalność wapnia.", NULL),
                ("agar", "E 406", "Emulgator" , "Klarująca, stabilizująca, emulgująca, zagęszczająca (nadaje środkom spożywczym konsystencję poprzez tworzenie żelu).", "Tylko w dużych dawkach może powodować wzdęcia.", NULL),
                ("acetylowany adypinian diskrobiowy", "E1422", "Emulgator" , "Zagęszczająca (zwiększa lepkość środków spożywczych), stabilizująca (umożliwia utrzymanie właściwości fizyczno-chemicznych środków spożywczych), wiążąca, nośnik.", "Jest naturalnym zagęszczaczem i stabilizatorem. Acetylowany adypinian diskrobiowy jest skrobią modyfikowaną, która jest zamiennikiem tłuszczu. Duży jej dodatek nie wpływa negatywnie na biodostępność witamin A i E. Związek ten jest nieszkodliwy.", NULL),
                ("acesulfam K", "E 950", "Substancje słodzące" , "Słodząca", "Jest syntetyczną substancją słodząca, która jest 200-krotnie słodsza od cukru. W większych stężeniach pozostawia gorzki i metaliczny posmak, z tego względu stosuje się E 950 w mieszaninach z innymi środkami słodzącymi. Acesulfam K nie jest metabolizowany w organizmie człowieka i ulega wydaleniu w niezmienionej postaci z moczem. W badaniu przeprowadzonym na myszach działanie genotoksyczne acesulfamu K polegało na interakcji tego związku z DNA, która prowadziła do uszkodzenia komórek. Kolejne badania nie potwierdziły genotoksycznego działania E 950.", NULL),
                ("brąz HT", "E 155", "barwniki syntetyczne" , "barwi na brązowo", "Jest częstą przyczyną biegunek i pokrzywek. Może wywołać astmę i reakcję alergiczne, dlatego nie powinny go spożywać osoby uczulone na aspirynę i dzieci.", NULL),
                ("błonnik roślinny", NULL, NULL , NULL, "zapobiega drażnieniu ścianek jelit przez trawiony pokarm, a także jego przyklejaniu się (co zapobiega niestrawności i gniciu), zmniejsza szybkość wchłaniania cukrów, eliminuje zaparcia, przedłuża uczucie sytości po posiłkach, dzięki czemu wspomaga odchudzanie, obniża poziom cholesterolu.", NULL),
                ("błonnik cytrynowy", NULL, NULL , NULL, "zapobiega drażnieniu ścianek jelit przez trawiony pokarm, a także jego przyklejaniu się (co zapobiega niestrawności i gniciu), zmniejsza szybkość wchłaniania cukrów, eliminuje zaparcia, przedłuża uczucie sytości po posiłkach, dzięki czemu wspomaga odchudzanie, obniża poziom cholesterolu.", NULL),
                ("błękit patentowy V", "E 131", "Barwniki" , "Barwi na niebiesko.", "syntetyczny, niebieski barwnik. Jest on nieszkodliwy dla zdrowia.", NULL),
                ("błękit brylantowy FCF", "E 133", "Barwniki" , "Barwi na niebiesko.", "Jest to barwnik syntetyczny. Może powodować reakcje alergiczne.", NULL),
                ("bio płatki jęczmienne", NULL, NULL , NULL, "Płatki jęczmienne są bogate w błonnik (rozpuszczalny w wodzie), fosfor, potas, magnez, wapń, żelazo oraz witaminy z grupy B. Rozpuszczalny błonnik pokarmowy przyczynia się do obniżenia poziomu cholesterolu we krwi oraz reguluje pracę przewodu pokarmowego (zapobiega zaparciom, wzdęciom).", NULL),
                ("BHT", "E 321", "Przeciwutleniacz syntetyczny" , "Przedłuża datę przydatności do spożycia.", "Pełna nazwa brzmi butylohydroksytoluen. BHT spożywany w dużych ilościach może spowodować raka wątroby, ponadto obserwowano symptomy pseudo-alergiczne. Z powodu efektów ubocznych, UE ograniczyła stosowanie BHT.", NULL),
                ("BHA", "E 320", "Przeciwutleniacz" , "Przeciwutleniająca, Konserwująca", "pełna nazwa tego przeciwutleniacza brzmi butylohydroksyanizol. BHA podejrzewany jest o możliwość wywoływania alergii. W dużych dawkach związek ten powoduje zaburzenia pracy wątroby. Uważa się, że w ilościach, w jakich jest dodawany do żywności jest nieszkodliwy.", NULL),
                ("betanina", "E 162", "barwniki naturalne" , "substancje nadające lub przywracające żywności barwę, obejmujące naturalne składniki żywności i naturalne źródła, które w normalnych warunkach ani nie są same spożywane jako żywność ani nie są stosowane jako typowe składniki żywności.", "uznawana za nieszkodliwą", NULL),
                ("beta-apo-karotenal", "E 160e", "Barwniki" , "Barwi na pomarańczowo-żółto.", "Barwnik naturalny uznawany za nieszkodliwy.", NULL),
                ("benzoesan sodu", "E 211", "Konserwant" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem spowodowanym obecnością mikroorganizmów lub chroni przed wzrostem mikroorganizmów patogennych.", "Odnotowano przypadki m. in. astmy, pokrzywki, kontaktowego zapalenia skóry, nadpobudliwości. Uważać powinni zwłaszcza alergicy, a zwłaszcza osoby uczulone na aspirynę. Mieszanina sztucznych barwników i benzoesanu sodu wpływa na wystąpienie nadpobudliwości u dzieci.", NULL),
                ("benzoesan potasu", "E 212", "Konserwant" , "Przedłuża datę przydatności do spożycia.", "U niektórych osób kwas benzoesowy i benzoesany mogą być przyczyną pseudo-alergicznych reakcji.", NULL),
                ("częściowo utwardzone tłuszcze roślinne", "", "" , "", "spożywanie dużych ilości utwardzonych kwasów tłuszczowych zwiększa ryzyko wystąpienia m. in. otyłości brzusznej, cukrzycy typu II, miażdżycy, chorób serca.", NULL),
                ("czerwień allura", "E 129", "Barwniki" , "Barwi na pomarańczowo-czerwono.", "Może wywołać reakcje u osób z nietolerancją na salicylany. W połączeniu z benzoesanami może mieć szkodliwy wpływ na aktywność i skupienie uwagi u dzieci.", NULL),
                ("czerń brylantowa", "E 151", "barwniki syntetyczne" , NULL, "syntetyczny barwnik, który może wywoływać nietolerancję u osób z nadwrażliwością na salicylany. Może negatywnie wpływać na nerki i żołądek. Niezalecany dzieciom.", NULL),
                ("cytrynian wapnia", "E 333", "środek buforujący; stabilizator" , NULL, "może wywoływać objawy u osób reagujących na glutaminian sodu. Ponadto cytryniany mogą fałszować wyniki badań laboratoryjnych krwi.", NULL),
                ("cytrynian sodu", "E 331", "Regulator kwasowości" , "Jako regulator kwasowości zmienia lub kontroluje kwasowość lub zasadowość środka spożywczego. Ponadto umożliwia utworzenie lub utrzymanie jednorodnej mieszaniny dwóch lub większej liczby niemieszających się faz, takich jak olej i woda w środkach spożywczych. Również przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem na skutek utleniania, takim jak jełczenie tłuszczu czy zmiana barwy.", "jest to syntetyczny regulator kwasowości, który uważany jest za nieszkodliwy. Może osłabiać albo wzmacniać działanie niektórych leków. Ponadto, cytryniany mogą wywoływać objawy u osób reagujących na glutaminian sodu.", NULL),
                ("cytrynian potasu", "E 332", "regulator kwasowości; stabilizator; przeciwutleniacz" , NULL, "mogą wywoływać objawy u osób wrażliwych na glutaminian sodu. Cytryniany mogą fałszować wyniki badań laboratoryjnych krwi.", NULL),
                ("cyklaminian sodu", "E 952", "Substancje słodzące" , "Słodząca", "Jest 30-50 razy słodszy od sacharozy. Cyklaminian w 37% jest wchłaniany, pozostały jest wydalany w postaci niezmienionej. Niestety może ulegać przemianom do cykloheksyloaminy, podejrzewanej o działanie kancerogenne. Amerykańskie Stowarzyszenie Dietetyczne (ADA) w 2004 roku potwierdziło, iż cyklaminiany nie stanowią zagrożenia dla zdrowia, jednakże postulowało o ograniczanie spożycia E 952 przez dzieci.", NULL),
                ("cukier i/lub syrop glukozowy i/lub syrop glukozowo-fruktozowy",NULL , NULL, NULL, "nadmierne spożywanie tych dwóch substancji może być przyczyną powstawania m. in. otyłości, cukrzycy typu 2. Mogą również wpływać na zwiększony poziom cholesterolu i ryzyko zakrzepów.", NULL),
                ("cukier i/lub syrop glukozowo-fruktozowy",NULL , NULL, NULL, "nadmierne spożywanie tych dwóch substancji może być przyczyną powstawania m. in. otyłości, cukrzycy typu 2. Mogą również wpływać na zwiększony poziom cholesterolu i ryzyko zakrzepów.", NULL),
                ("chlorek wapnia", "E 509", "syntetyczny wzmacniacz tekstury i stabilizator" , NULL, "jest to wzmacniacz tekstury i stabilizator. Zarówno wapń jak i chlor są niezbędnymi składnikami mineralnymi w diecie. Nie należy się martwić jednak o przekroczenie maksymalnej dawki na zapotrzebowanie tych pierwiastków. Chlorek wapnia jest nieszkodliwy.", NULL),
                ("chlorek potasu", "E 508", NULL , "regulator kwasowości", "w niskich dawkach uznawany jest za nieszkodliwy. Wysokie dawki mogą wywołać problemy układu pokarmowego (nudności, wymioty).", NULL),
                ("chlorek magnezu", "E 511", "regulator kwasowości, stabilizator" , NULL, "Spożyty w nadmiarze może mieć działanie przeczyszczające.", NULL),
                ("dwutlenek węgla", "E 290", "Konserwant" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem spowodowanym obecnością mikroorganizmów lub chroni przed wzrostem mikroorganizmów patogennych.", "Naturalny gaz, który uważany jest za nieszkodliwy.", NULL),
                ("dwutlenek tytanu", "E 171", "barwnik" , NULL, "w zastosowaniach spożywczych uznawany za nieszkodliwy. Jest syntetycznym, mineralnym, białym barwnikiem.", NULL),
                ("dwutlenek siarki", "E 220", "Konserwant" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem spowodowanym obecnością mikroorganizmów lub chroni przed wzrostem mikroorganizmów patogennych.", "Syntetycznie otrzymywany konserwant i przeciwutleniacz. Powoduje straty witaminy A i B1 w produktach spożywczych. U osób wrażliwych może wywołać bóle głowy i nudności. Osoby chorujące na astmę lub inne choroby układu oddechowego są bardziej podatne na działanie dwutlenku siarki. Dopuszczalna dzienna dawka dwutlenku siarki wynosi 0,7 mg/kg m. c. Wypicie dwóch kieliszków zwłaszcza słodkiego białego wina (do którego został dodany E 220 w ilości 300-400 mg/l) może spowodować przekroczenie dopuszczalnego dziennego pobrania. Odradza się częste spożywanie.", NULL),
                ("dwutlenek krzemu", "E 551", "środek przeciwzbrylający, substancja klarująca" , NULL, "uznawany za nieszkodliwy. Nie jest wchłaniany w organizmie.", NULL),
                ("difosforany", "E 450", "Substancja buforująca" , "Buforująca, Maskująca, Regulująca kwasowość, Klarująca, Spulchniająca, Stabilizująca, Emulgująca, Polepszająca.", "W niskich dawkach uznawane za nieszkodliwe. Spożywane w nadmiarze mogą pogarszać wchłanianie wapnia, magnezu i żelaza oraz powodować osteoporozę i odkładanie się wapnia. Ponadto nadmiar może spowodować uszkodzenie nerek.", NULL),
                ("etylowanilina", NULL, "aromaty" , "Nadają produktom charakterystyczny aromat i smak.", "jest substancją syntetyczną, nie występuje w przyrodzie. Jest 3,5-krotnie bardziej aromatyczna niż wanilina, a także bardziej trwała podczas przechowywania.", NULL),
                ("estry sacharozy i kwasów tłuszczowych", "E 47", "Stabilizator, emulgator" , "Stabilizującą i emulgująca.", "Produkt jest trawiony do cukrów i tłuszczów. Substancje wchodzące w skład E473 są wytwarzane przez organizm w sposób naturalny, podczas procesu trawienia naturalnych tłuszczów. Zazwyczaj E 473 jest pochodzenia roślinnego, ale nie jest to regułą (tylko producent może udzielić konkretnej informacji).", NULL),
                ("estry kwasów tłuszczowych i poliglicerolu", "E 475", "Emulgator" , "Emulgująca, Nośnik, Zagęszczająca", "Organizm metabolizuje ten związek tak samo jak naturalny tłuszcz. Pomimo, że w produkcji E 475 wykorzystywane są głównie oleje roślinne, zdarza się, że stosowane są także tłuszcze zwierzęce (również wieprzowe).", NULL),
                ("estry kwasów tłuszczowych i kwasu askorbinowego", "E 304", "Przeciwutleniacz" , "Przeciwutleniająca, konserwująca i stabilizująca", "Inne nazwy tego związku to palmitynian askorbylu i stearynian askorbylu. Uważany jest za nieszkodliwy w zastosowaniach spożywczych.", NULL),
                ("estry glicerolu i żywicy roślinnej", "E 445", "Emulgator" , "Stabilizującą i emulgująca.", "Do tej pory przeprowadzono zbyt małą ilość badań dotyczących tego związku, dlatego nie ma danych na temat jego bezpieczeństwa. Z tego względu zalecana jest ostrożność.", NULL),
                ("erytrytol", "E 968", "Substancje słodzące" , "Słodząca, wzmacniacz lub nośnik aromatu.", "Substancja słodząca pochodzenia syntetycznego. Przeprowadzone badania dotyczące toksyczności erytrytolu są bardzo obiecujące - nawet wysokie dawki substancji nie wykazały żadnych efektów toksycznych. Oprócz funkcji słodzącej związek ten może znaleźć zastosowanie w produktach spożywczych, m. in. jako wzmacniacz lub nośnik aromatu. Kaloryczność E 968 wynosi 0,2-0,4 kcal/g, natomiast indeks glikemiczny wynosi zero. Z tego względu może być bez przeszkód stosowany przez osoby chore na cukrzycę. Jego ogromną zaletą jest fakt, że nie wywołuje ani wzdęć, ani biegunek - efekt przeczyszczający pozostałych polioli jest znacznie wyższy niż erytrytolu.", NULL),
                ("ekstrakt z papryki; kapsantyna; kapsorubina", "E 160c", "Barwniki" , "Barwi na pomarańczowo-czerwono.", "Nieszkodliwy w zastosowaniach spożywczych. Może mieć korzystny wpływ na zdrowie, ponieważ E 160c należy do grupy karotenoidów pełniących wiele ważnych funkcji w organizmie. Karotenoidy mają ochronny wpływ na oczy nie tylko ze względu na to, że są prekursorami witaminy A. Przeciwdziałają również takim chorobom oczu związanym z wiekiem, jak zaćma i zwyrodnienie plamki żółtej. Prowadzono badania, które wykazały korzystny wpływ karotenoidów w prewencji nowotworów ze względu na ich antyoksydacyjne właściwości.", NULL),
                ("kapsorubina", "E 160c", "Barwniki" , "Barwi na pomarańczowo-czerwono.", "Nieszkodliwy w zastosowaniach spożywczych. Może mieć korzystny wpływ na zdrowie, ponieważ E 160c należy do grupy karotenoidów pełniących wiele ważnych funkcji w organizmie. Karotenoidy mają ochronny wpływ na oczy nie tylko ze względu na to, że są prekursorami witaminy A. Przeciwdziałają również takim chorobom oczu związanym z wiekiem, jak zaćma i zwyrodnienie plamki żółtej. Prowadzono badania, które wykazały korzystny wpływ karotenoidów w prewencji nowotworów ze względu na ich antyoksydacyjne właściwości.", NULL),
                ("kapsantyna", "E 160c", "Barwniki" , "Barwi na pomarańczowo-czerwono.", "Nieszkodliwy w zastosowaniach spożywczych. Może mieć korzystny wpływ na zdrowie, ponieważ E 160c należy do grupy karotenoidów pełniących wiele ważnych funkcji w organizmie. Karotenoidy mają ochronny wpływ na oczy nie tylko ze względu na to, że są prekursorami witaminy A. Przeciwdziałają również takim chorobom oczu związanym z wiekiem, jak zaćma i zwyrodnienie plamki żółtej. Prowadzono badania, które wykazały korzystny wpływ karotenoidów w prewencji nowotworów ze względu na ich antyoksydacyjne właściwości.", NULL),
                ("ekstrakt słodowy jęczmienny", NULL, NULL, NULL, "słód jest naturalnym środkiem słodzącym i nadaje dodatkowo przyjemny, apetyczny kolor. Brzeczka słodowa oprócz swoich podstawowych składników (maltoza, glukoza i dekstryny) zawiera również szereg cennych substancji pochodzących ze słodu: produkty hydrolizy białek (aminokwasy i peptydy), witaminy, sole mineralne, garbniki oraz kwasy organiczne.", NULL),
                ("ekstrakt drożdżowy", NULL, "substancje aromatyczne" , "Nadają smak i zapach produktom spożywczym.", "jest powszechnie stosowany jako substancja aromatyzująca i wzmacniająca smak produktów spożywczych. Kodeks Chemii Żywności (The Food Chemical Codex) definiuje ekstrakty drożdżowe jako produkty składające się z rozpuszczalnych w wodzie składników komórek drożdżowych, przede wszystkim aminokwasów, peptydów, węglowodanów i soli. Ekstrakty drożdżowe są bogate w azot, witaminy i inne składniki stymulujące wzrost mikroorganizmów.", NULL),
                ("ekspandowane nasiona amarantusa", NULL, NULL, NULL, "Ekspandowanie może mieć na celu: uszlachetnienie żywności (poprzez wyeliminowanie antyżywieniowych składników, zwiększenie przyswajalności składników odżywczych oraz nadanie specjalnego smaku) lub wytworzenie produktów przeznaczonych do bezpośredniego spożycia.", NULL),
                ("fruktoza", NULL, NULL, NULL, "jest cukrem owocowym należącym do grupy monosacharydów. Występuje głównie w miodzie i owocach. Często jest mylona i niesłusznie zaliczana do grupy niskokalorycznych substancji słodzących. Spożycie większej ilości fruktozy może prowadzić do rozwoju hipertriglicerydemii oraz do zwiększonej koncentracji frakcji VLDL cholesterolu. Podczas dłuższego spożywania znacznych jej ilości może dojść do zmniejszonej odpowiedzi insulinowej oraz wytwarzania leptyny, co w konsekwencji skutkuje przyrostem tkanki tłuszczowej.", NULL),
                ("fosforany wapnia", "E 341", "środek buforujący; środek maskujący" , NULL, "uznawane za nieszkodliwe.", NULL),
                ("fosforany sodu", "E 339", "regulator kwasowości; emulgator", NULL, "w niskich dawkach uznawane za nieszkodliwe. W organizmie powinna istnieć określona proporcja pomiędzy ilością fosforu i wapnia. Jeśli do organizmu dostarczymy za dużo fosforu, wówczas może to zakłócić przyswajanie innych substancji mineralnych. Z tego względu odradza się częste spożywanie.", NULL),
                ("fosforany potasu", "E 340", "regulator kwasowości, stabilizator", NULL, "uważane za nieszkodliwe", NULL),
                ("guma tara", "E 417", NULL , "zagęstnik", "środek zagęszczający otrzymywany z nasion roślin strączkowych tara. Uznawana jest za nieszkodliwą.", NULL),
                ("guma ksantanowa", "E 415", "emulgator" , "Stabilizująca, emulgująca, zagęszczająca", "syntetyczny środek zagęszczający i stabilizujący na bazie roślinnej. Wytwarzany na drodze fermentacji węglowodanów przez szczepy bakterii. Bezpieczny dla zdrowia.", NULL),
                ("guma guar", "E 412", "substancje żelujące" , "nadają środkom spożywczym konsystencję poprzez tworzenie żelu", "E 412 jest naturalnym, roślinnym środkiem zagęszczającym i stabilizatorem. Guma guar uważana jest za nieszkodliwą, jednak zdarzają się przypadki wystąpienia po jej spożyciu reakcji alergicznych w postaci zaburzeń żołądkowo-jelitowych, astmy i egzemy kontaktowej. Nadmierne spożycie może prowadzić do nudności, wzdęć i biegunek. Guma guar pęcznieje w żołądku, co daje uczucie sytości. Jako rozpuszczalny w wodzie błonnik, pomaga w leczeniu zaparć, sprzyja namnażaniu się korzystnej flory bakteryjnej, jest pomocna w utrzymaniu optymalnego pH w jelitach oraz w prewencji nowotworów jelita grubego.", NULL),
                ("guma arabska", "E 414", "środek zagęszczający, stabilizator i emulgator" , NULL, "uważana za nieszkodliwą, ale na składnik ten powinni uważać alergicy.", NULL),
                ("guanylan disodowy", "E 627", "wzmacniacz smaku i zapachu" , NULL, "niemożliwe jest obecnie wydanie wiążącej opinii.", NULL),
                ("glutaminian sodu", "E 621", "wzmacniacz smaku i zapachu" , "Wzmacniająca smak i zapach", "Jest uważany m. in. przez WHO (Światowa Organizacja Zdrowia), FDA (Agencja ds. Żywności i Leków), IŻŻ (Instytut Żywności i Żywienia) za bezpieczny, również dla ciężarnych i małych dzieci. Jednak istnieją badania naukowe, które nie potwierdzają jego dobrej opinii.", NULL),
                ("glukuronolakton", NULL, NULL, NULL, "ma działanie regenerujące, przyspiesza wydalanie z organizmu szkodliwych substancji przemiany materii.", NULL),
                ("glikozydy stewiolowe", "E 960", "Substancje słodzące" , "Słodząca", "Glikozydy stewiolowe to ogólna nazwa 9 różnorodnych pochodnych stewiolu występujących w Steveia rebaudiana. W mieszaninie glikozydów obecnej w ekstrakcie z liści ok. 65% stanowi stewiozyd, a około 25% rebaudiozyd A, pozostałe to rebaudiozyd B, C, D, E, F, duclozyd A i C oraz stewiolbiozyd. Stewiozyd oprócz właściwości słodzących (200–300 razy słodszy od sacharozy) cechuje się nieco gorzkim i lukrecjowym posmakiem, który jest słabszy w przypadku rebaudiozydu A (300–400 razy słodszy od sacharozy). W przewodzie pokarmowym glikozydy stewiolowe nie są trawione, lecz ulegają rozkładowi do stewiolu przy udziale bakterii obecnych w jelicie grubym. Ponieważ glikozydy stewiolowe rozkładane są dopiero na poziomie jelita grubego, uwolniona z nich glukoza nie wchłania się i zostaje zużyta przez bakterie jelitowe. Dlatego stewia nie wnosi energii do organizmu człowieka i należy ją traktować jako bezkaloryczną substancję słodzącą. Wykazano również, iż spożycie glikozydów stewiolowych nie podnosi poziomu glukozy w surowicy krwi. Kolejną zaletą stewiozydów jest ograniczanie próchnicy zębów powodowanej przez Streptococcus mutans.", NULL),
                ("glicerol", "E 422", "środek utrzymujący wilgotność, emulgator", NULL, "w niskich dawkach nieszkodliwy.", NULL),
                ("galusan propylu", "E 310", "Przeciwutleniacz", "Przeciwutleniająca", "Jest syntetycznym przeciwutleniaczem. Badania toksykologiczne z udziałem szczurów wykazały, że związek ten może uszkadzać wątrobę. Tego dodatku powinny się wystrzegać osoby chore na astmę, dzieci oraz uczuleni na aspirynę. Istnieje możliwość, że substancja ta utrudnia wchłanianie żelaza.", NULL),
                ("hydroksypropylometyloceluloza", "E 464", NULL, "emulgator, zagęstnik, substancja żelująca, stabilizator", "może wywoływać reakcje alergiczne, jednak uznawana jest za nieszkodliwą w zastosowaniach spożywczych.", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
                ("", "", "", "", "", NULL),
""")

cursor.execute(""" SELECT * FROM substances""")
print(cursor.fetchall())

conn.commit()

conn.close()
