import sqlite3 as sql

conn = sql.connect('product_substances.db')

cursor = conn.cursor()

# cleaning table - only for debug
cursor.execute("DROP TABLE IF EXISTS substances")

# create table of substances
cursor.execute(""" CREATE TABLE IF NOT EXISTS substances(
                name_of_substance text,
                e_code text,
                group text,
                function text,
                description text,
                harmfulness integer
)""")

# insert all substances into the tasble
cursor.execute(""" INSERT INTO substances VALUES
                ("5'-rybonukleotydy disodowe", "E 635", "Wzmacniacz smaku i zapachu" , "Substancje wzmacniające istniejący smak lub zapach środków spożywczych.", "Pełni rolę wzmacniacza smaku i zapachu. Istnieje wiele doniesień o niekorzystnym wpływie tego związku na nasze zdrowie, jednak nie jest możliwe wydanie wiążącej opinii.", NULL),
                ("azotyn sodu", "E 250", "Konserwant" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem spowodowanym obecnością mikroorganizmów lub chroni przed wzrostem mikroorganizmów patogennych.", "Jest dodawany do przetworów mięsnych i wyrobów garmażeryjnych w postaci mieszanki peklującej, w celu zabezpieczenia przed rozwojem bakterii beztlenowych. Jednak nadmierne pobranie azotynów może prowadzić do methemoglobinemii. Najbardziej narażone są niemowlęta. Nie należy ogrzewać peklowanych przetworów mięsnych, ponieważ w temperaturze powyżej 150°C powstają rakotwórcze nitrozoaminy. Przeprowadzono próby zastąpienia azotynów innymi substancjami, które hamowałyby wzrost Clostridium botulinum lub wytwarzanie toksyny botulinowej, jednak azotyny pozostają jedynym skutecznym środkiem.", NULL),
                ("azotan potasu", "E 252", "Konserwant" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem spowodowanym obecnością mikroorganizmów lub chroni przed wzrostem mikroorganizmów patogennych.", "Syntetyczny konserwant. Azotany są związkami chemicznymi o stosunkowo niskiej toksyczności dla ludzi, ale w organizmie ulegają przemianom do groźnych azotynów. Nadmierne pobranie azotynów lub redukcja azotanów do azotynów mogą doprowadzić do methemoglobinemii objawiającej się: sinicą, dusznością, sennością, bólem brzucha.", NULL),
                ("azorubina", "E 122", "barwniki syntetyczne" , "Barwi na czerwono.", "Jest syntetycznym barwnikiem, którego powinny unikać osoby uczulone na aspirynę. Może mieć szkodliwy wpływ na aktywność i skupienie uwagi u dzieci.", NULL),
                ("aspartam", "E 951", "Substancje słodzące" , "Słodząca, wzmacniacz smaku.", "Jest syntetyczną substancją słodzącą i wzmacniaczem smaku, która jest, aż 160-200 razy słodszy od sacharozy. Aspartam podczas trawienia rozkłada się na kwas asparaginowy, fenyloalaninę i nieznaczne ilości metanolu. Dlatego osoby chore na fenyloketonurię powinny zachować ostrożność! U tych osób wysokie stężenia fenyloalaniny oraz jej metabolitów we krwi działają toksycznie oraz mogą prowadzić do nieodwracalnego uszkodzenia mózgu. Z tego powodu na każdym opakowaniu jednostkowym produktu zawierającego aspartam musi być umieszczone ostrzeżenie: „zawiera źródło fenyloalaniny”. Niektóre badania wykazały, że po konsumpcji aspartamu mogą wystąpić w organizmie człowieka różne reakcje ze strony układu nerwowego, takie jak: bóle głowy, napady padaczkowe, upośledzenie percepcji, stany podniecenia, frustracji, depresji i ogólnego zaburzenia ustroju. Aspartam jest to substancja uznana za bezpieczną pod warunkiem zachowania dozwolonej dziennej dawki, czyli 40 mg aspartamu na 1 kg masy ciała.", NULL),
                ("askorbinian sodu", "E 301", "Przeciwutleniacz" , "Przeciwutleniająca, Regulująca kwasowość, Stabilizująca", "Nieszkodliwy w zastosowaniach spożywczych.", NULL),
                ("aromaty: jajo; wanilina", NULL, NULL , NULL, "wanilina jest substancją występującą naturalnie we włóknach drzew iglastych. Otrzymuje się ją z ligniny z drewna jodły (i innych drzew iglastych), albo w sposób syntetyczny z eugenolu lub gwajakolu. Stosowana jest jako substancja zapachowo-smakowa. Wanilina, pomimo że jest wyodrębniana z naturalnych surowców, jest zaliczana do syntetycznych środków zapachowych. Uznawana jest za bezpieczną dla zdrowia człowieka.", NULL),
                ("aromat dymu wędzarniczego", NULL, NULL , NULL, "ma właściwości barwiące i aromatyzujące.", NULL),
                ("antocyjany", "E 163", "Barwniki" , "Barwią na czerwono-purpurowo.", "Naturalne barwniki, które nie tylko są bezpieczne dla zdrowia, ale uważa się, że pełnią funkcje ochronne w organizmie. Antocyjany uszczelniają naczynia włosowate, zapobiegają obrzękom i posiadają aktywność przeciwzapalną. Ze względu na działanie antyoksydacyjne odgrywają ważną rolę w prewencji chorób nowotworowych. Antocyjany jako barwniki żywności wykazują działanie chroniące produkty spożywcze przed zepsuciem, ponieważ wykazują antagonistyczną aktywność wobec niektórych bakterii, wirusów i grzybów.", NULL),
                ("annato", "E 160b", "Barwniki naturalne" , "Nadaje lub przywraca żywności barwę na żółto-pomarańczowo.", "Barwnik żółty do pomarańczowego, kolor pochodzi od karotenoidów: biksyny i norbiksyny. Nie jest możliwe wydanie jednoznacznej opinii, jednak wiele badań wykazało niekorzystny wpływ tej substancji na zdrowie (zwłaszcza dzieci). Konieczne są dalsze badania.", NULL),
                ("amarant", "E 123", "Barwniki" , "Barwi na ciemnoczerwowno.", "Może nasilać objawy nietolerancji salicylanów oraz objawy astmy.", NULL),
                ("alginian sodu", "E 401", "Emulgator" , "Stabilizująca, Emulgująca, Rozpuszczalnik, Zagęszczająca.", "Naturalny, roślinny środek zagęszczający, do powlekania i substancja żelująca, która należy do grupy naturalnych hydrokoloidów pozyskiwanych z wodorostów morskich (alg brunatnych). Mogą korzystnie wpływać na zdrowie.", NULL),
                ("alginian propan-1;2-diolu", "E 405", "Emulgator" , "Klarująca, Stabilizująca, Emulgująca, Zagęszczająca", "Naturalny, roślinny środek zagęszczający, emulgator. U niektórych osób może powodować reakcje alergiczne, a w dużych dawkach efekt przeczyszczający.", NULL),
                ("alfa-tokoferol", "E 307", "Przeciwutleniacze" , "Przedłuża okres przydatności środków spożywczych do spożycia poprzez ochronę przed zepsuciem na skutek utleniania, takim jak jełczenie tłuszczu czy zmiana barwy.", "jest to syntetycznie produkowana witamina E. Witamina E uważana jest za jeden z najlepszych biologicznych przeciwutleniaczy. Dzięki właściwości antyoksydacyjnej zmniejsza ryzyko rozwoju chorób sercowo-naczyniowych oraz zmniejsza nasilenie procesów kancerogenezy. Spowalnia również ogólnoustrojowe procesy starzenia się organizmu, których przejawem jest m.in. spadek odporności.", NULL),
                ("aktywna mikroflora jogurtowa i dodatkowo kultury probiotyczne Lactobacillus acidophilus LA- 5; Bifidobacterium BB - 12", NULL, NULL , NULL, "probiotyki korzystnie działają w schorzeniach układu pokarmowego (syndrom jelita drażliwego, zapalenie jelit, biegunka), schorzeniach alergicznych (atopowe zapalenie skóry), a także zwiększają odporność organizmu. Bifidobakterie wzbogacają organizm człowieka w witaminy: B1, B2, B6, kwas foliowy i nikotynowy, korzystnie działają na przyswajalność wapnia.", NULL),
                ("agar", "E 406", "Emulgator" , "Klarująca, stabilizująca, emulgująca, zagęszczająca (nadaje środkom spożywczym konsystencję poprzez tworzenie żelu).", "Tylko w dużych dawkach może powodować wzdęcia.", NULL),
                ("acetylowany adypinian diskrobiowy", "E1422", "Emulgator" , "Zagęszczająca (zwiększa lepkość środków spożywczych), stabilizująca (umożliwia utrzymanie właściwości fizyczno-chemicznych środków spożywczych), wiążąca, nośnik.", "Jest naturalnym zagęszczaczem i stabilizatorem. Acetylowany adypinian diskrobiowy jest skrobią modyfikowaną, która jest zamiennikiem tłuszczu. Duży jej dodatek nie wpływa negatywnie na biodostępność witamin A i E. Związek ten jest nieszkodliwy.", NULL),
                ("acesulfam K", "E 950", "Substancje słodzące" , "Słodząca", "Jest syntetyczną substancją słodząca, która jest 200-krotnie słodsza od cukru. W większych stężeniach pozostawia gorzki i metaliczny posmak, z tego względu stosuje się E 950 w mieszaninach z innymi środkami słodzącymi. Acesulfam K nie jest metabolizowany w organizmie człowieka i ulega wydaleniu w niezmienionej postaci z moczem. W badaniu przeprowadzonym na myszach działanie genotoksyczne acesulfamu K polegało na interakcji tego związku z DNA, która prowadziła do uszkodzenia komórek. Kolejne badania nie potwierdziły genotoksycznego działania E 950.", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
                ("", "", "" , "", "", NULL),
""")

cursor.execute(""" SELECT * FROM substances""")
print(cursor.fetchall())

conn.commit()

conn.close()
